[features]
seeds = false
skip-lint = false
[programs.devnet]
candy_machine_program = "2KXJgDqYECfjKKGqErJRsfTvT7NAMFqZEELmVpPNS42q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/demo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
